route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'healer_webhook'

receivers:
- name: 'healer_webhook'
  webhook_configs:
  - url: 'http://healer:5000/heal'
    send_resolved: true