@startuml activity-07-breeding
title Деятельность: учёт пар для разведения и решения по потомству

|Администрация|
start
:Поиск особей одного вида\nс подходящими полом/возрастом;
|Система|
:Проверить физическое состояние\nи отсутствие противопоказаний;
if (Пара допустима?) then (да)
  |Администрация|
  :Зафиксировать пару\nдля возможного разведения;
  |Система|
  :Вести статус пары\n(активна / приостановлена);
else (нет)
  :Отклонить с указанием причины;
  stop
endif

|Система|
if (Зафиксировано появление\nпотомства?) then (да)
  |Администрация|
  :Открыть решение\nо судьбе потомства;
  switch (Вариант решения?)
  case ( Оставить в зоопарке )
    :Запланировать условия\nсодержания (клетка, рацион);
    |Система|
    :Создать карточки особей\nдля потомства;
  case ( Обмен с другим зоопарком )
    :Согласовать обмен\nс внешней стороной;
    |Система|
    :Оформить передачу данных\nи статусы согласования;
  case ( Передача в другой зоопарк )
    :Согласовать передачу;
    |Система|
    :Оформить документ обмена\nбез встречного получения;
  endswitch
else (нет)
  :Ожидать события\nили закрыть пару;
endif
stop
@enduml
